### ISSUE TITLE
Error "Cannot read property 'toChecksumAddress' of undefined" when calling Project#createProxy

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#1087]
Originally reported [here](https://github.com/zeppelinos/zos/issues/863#issuecomment-507699883).

```
contract = await project.createProxy(MyContract, {
      initMethod: 'initialize',
      initArgs: [
        owner,
        address_a,
        address_b,
        address_c,
        address_d
      ]
    });
```

     TypeError: Cannot read property 'toChecksumAddress' of undefined
      at Object.toAddress (node_modules/zos-lib/src/utils/Addresses.ts:12:21)
      at new ProxyAdmin (node_modules/zos-lib/src/proxy/ProxyAdmin.ts:39:20)
      at Function.<anonymous> (node_modules/zos-lib/src/proxy/ProxyAdmin.ts:34:12)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/zos-lib/lib/proxy/ProxyAdmin.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by spalladino** [comment]
Hey @chentschel, this looks like an issue when importing `web3-utils`. Could you confirm which version of the `web3` library you have installed?
