### ISSUE TITLE
1 test not passing when blocktime != 0

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos#173]
When running cli unit tests with blocktime != 0, I'm getting one error:
```
1) Contract: push script
       an app with dependency
         "before each" hook: deploying dependency for "should include deployment addresses":
     Error: Error: VM Exception while processing transaction: revert
      at sendTransaction (/home/ajs/zos/packages/lib/lib/utils/Transactions.js:40:70)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

See https://github.com/zeppelinos/zos/issues/170 for more info.

**Comment by spalladino** [comment]
Pending https://github.com/OpenZeppelin/openzeppelin-test-environment/issues/31 to reproduce
