### ISSUE TITLE
Fail to deploy to rinkeby using `truffle-hdwallet-provider` when having dependencies linked.

### ISSUE THREAD

**Issue by jcarpanelli** [zeppelinos/zos#297]
I'm trying to deploy an unpublished project with a linked dependency (eth-did-registry), and I'm getting the following error:
```console
foo@bar:~$ npx zos push --network infura_rinkeby --skip-compile --deploy-dependencies --verbose
[NetworkAppController] Deploying ethr-did-registry contracts
[Package] Deploying new Package...
[Package] Deployed Package 0xb1d6f84fbcd4d497fb7d4d3a4b9bf4535216a0a8
[Package] Adding new version...
[ImplementationDirectory] Deploying new ImplementationDirectory...
[ImplementationDirectory] Deployed ImplementationDirectory at 0xca9557b6e2140e7eaf1fd9ce249f2294ea486a28
[Error] Error: Failed deployment of dependency ethr-did-registry with error: Error: ProviderError: gas required exceeds allowance or always failing transaction
    at allPromisesOrError (/home/jota/work/zeppelin/zos/packages/cli/lib/utils/async.js:36:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

`truffle.js` config:

```javascript
infura_rinkeby: {
  name: "infura_rinkeby",
  network_id: "4",
  provider:  () =>  {
    return new HDWalletProvider(process.env.WALLET_MNEMONIC, `https://rinkeby.infura.io/v3/${process.env.INFURA_API_KEY}`)
  },
  gas: 8000000,
  gasPrice: 22000000000,
  from: '0x1e...'
},

```

I'm running the same command using a rinkeby geth node with the same gas/gasPrice and it works fine.

EDIT: I'm having the same problem using `truffle-hdwallet-provider` and the geth  node, so I would assume that the problem is not infura, but `truffle-hdwallet-provider`.

**Comment by jcarpanelli** [comment]
This issue might be related to https://github.com/trufflesuite/truffle-hdwallet-provider/issues/59

**Comment by godsflaw** [comment]
I'm watching this issue too as I have a similar problem that I chased down to `estimateGas`:
```
$ zos push --skip-compile --verbose --network kovan
[AppDeployer] Deploying new UpgradeabilityProxyFactory...
[AppDeployer] Deployed UpgradeabilityProxyFactory 0x004edfcca0dae827db9d64a6784f682edc43be1c
[AppDeployer] Deploying new Package...
[AppDeployer] Deployed Package 0x788576a9b880e0a2896868040f5797dfde7e3416
[AppDeployer] Deploying new AppDirectory...
[AppDeployer] Deployed AppDirectory 0x5232911af41b6bcd36fdf24f9805a8f404a0f171
[AppDeployer] Adding new version...
[AppDeployer] Added version 1.0.14
[AppDeployer] Deploying new PackagedApp...
[ZosNetworkFile] Successfully written zos.kovan.json
[Error] Error: ProviderError: Transaction execution error.
    at deploy (/usr/local/lib/node_modules/zos/node_modules/zos-lib/lib/utils/Transactions.js:57:70)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'm happy to try debugging on my side.  The difference with me is, I can deploy to `rinkeby` and `ropsten`, but get failures on `kovan`.  There is also the possibility that my problem fails in a similar place but is unrelated to this issue.
