### ISSUE TITLE
Upgrading to ZOS-lib 2.1.1 is causing the build to break

### ISSUE THREAD

**Issue by hardlydifficult** [zeppelinos/zos#617]
Upgrading ZOS-lib from 2.1.0 to 2.1.1 causes the build to break with errors such as:

```
Error: Invalid JSON RPC response: undefined
      at Object.InvalidResponse (node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at RequestManager.send (node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:61:1)
      at Eth.get [as accounts] (node_modules/truffle/build/webpack:/~/web3/lib/web3/property.js:107:1)
      at Object._provideContractForTesting (node_modules/zos-lib/lib/utils/Contracts.js:118:49)
      at Object._getFromPath (node_modules/zos-lib/lib/utils/Contracts.js:106:51)
      at Object.getFromLocal (node_modules/zos-lib/lib/utils/Contracts.js:69:17)
      at contractNames.map.contractName (node_modules/zos/lib/models/network/NetworkController.js:219:47)
      at Array.map (<anonymous>)
      at NetworkController._getAllSolidityLibNames (node_modules/zos/lib/models/network/NetworkController.js:218:36)
      at NetworkController._solidityLibsForPush (node_modules/zos/lib/models/network/NetworkController.js:142:27)
      at exports.default (node_modules/zos/lib/models/TestHelper.js:22:20)
```

```
TypeError: Cannot read property 'call' of undefined
      at node_modules/truffle/build/webpack:/packages/truffle-core/lib/testing/testrunner.js:76:1
      at node_modules/truffle/build/webpack:/~/async/dist/async.js:1140:1
      at node_modules/truffle/build/webpack:/~/async/dist/async.js:473:1
      at iteratorCallback (node_modules/truffle/build/webpack:/~/async/dist/async.js:1064:1)
      at node_modules/truffle/build/webpack:/~/async/dist/async.js:969:1
      at node_modules/truffle/build/webpack:/~/async/dist/async.js:1137:1
      at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

You can see more details in this greenkeeper issue including a link to the Travis build: https://github.com/unlock-protocol/unlock/issues/1308

I'm not sure how to debug this further.  Please advise, thanks.

**Comment by spalladino** [comment]
Hey @hardlydifficult! The problem, as discovered by @facuspagnuolo (all credits on the following research go to him!), is related to an old issue related to how truffle managed dependencies, that resurfaced after a recent release of truffle-flattener. As part of the 2.1.1 release, the version of flattener was upgraded from 1.2.10 to 1.2.11, and flattener itself updated truffle-resolver from 4.0.4 to 4.0.5 in the 1.2.11 release.

**The problem is that truffle-resolver inadvertently upgrades from web3 0.x to web3 1.0 in a patch release**, which breaks basically anything that depends on it. We had experienced this a few weeks ago, and fixed it by pinning the version of all truffle dependencies; but it has bitten us again due to the transitive dependency on flattener. We will release a version 2.1.2 soon with all dependencies pinned, which should fix the issue. 

In the meantime, as a workaround, if you manually install `truffle-flattener@1.2.10`, the tests on your repository pass, with both zos-lib 2.1.0 and 2.1.1.

**Comment by facuspagnuolo** [comment]
Fixed! please see https://github.com/unlock-protocol/unlock/pull/1320
