### ISSUE TITLE
truffle-migrate network is not defined

### ISSUE THREAD

**Issue by imbenwolf** [zeppelinos/zos#734]
When following the instructions from truffle-migrate inside examples/truffle-migrate (e.g cloning and following "Running this project"), I get the following error:

```
Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0x1da53944037a0407ff9137791e3cea87d4c703da6465c939916f572408b3f772
  Migrations: 0x4ae94c5e7c63b8f2a69b1b2a8e3a9a4b8c64a032
Saving successful migration to network...
  ... 0xb942dc8f1dcabd618aff308378ec53ccc6a66f03288ebfa71bd5c1c695feccc2
Saving artifacts...
Running migration: 2_deploy_v0.js
  Running step...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
ReferenceError: network is not defined
    at deployer.then (C:\Users\test\Documents\work\test\zos\examples\truffle-migrate\migrations\2_deploy_v0.js:18:97)
    at C:\Users\test\Documents\work\test\zos\examples\truffle-migrate\node_modules\truffle\build\webpack:\packages\truffle-deployer\index.js:68:1
    at C:\Users\test\Documents\work\test\zos\examples\truffle-migrate\node_modules\truffle\build\webpack:\packages\truffle-deployer\src\deferredchain.js:20:1
error Command failed with exit code 1.
```

**Comment by spalladino** [comment]
@imbenwolf there was a bug on the script, please check out #741 for the fix. Apologies for the issue!

**Comment by imbenwolf** [comment]
Thanks @spalladino for the fix and the fast response :D One question though: How would I call the new "add" function of the v1 contract? The alias does not change the abi inside the json artifact...

**Comment by spalladino** [comment]
@imbenwolf maybe something along the following lines...?

```js
const MyContract = artifacts.require('MyContract_v0');
const MyContractV1 = artifacts.require('MyContract_v1');

const address = (await MyContract.deployed()).address;
const deployed = await MyContractV1.at(address);
await deployed.add(10);
```
