### ISSUE TITLE
Tests that work with zos@2.2.0 break with zos@v2.3.0-alpha.0 

### ISSUE THREAD

**Issue by crazyrabbitLTC** [zeppelinos/zos#787]
This seems like a bug: Tests that run fine under zos@2.2.0 suddenly break under zos@v2.3.0-alpha.0

I have tested this by running tests under 2.2.0, uninstalling zos, installing 2.3.0-alpha.0, running tests (it breaks), uninstalling zos, and reinstalling 2.2.0, running tests (runs fine).

The error is: 

 ```
 1) Contract: builder
       "before each" hook for "Should have no languages at first deploy":
     Failed deployment of dependency openzeppelin-eth with error: Provider not set or invalid
  Error: Provider not set or invalid
      at Object.InvalidProvider (node_modules/web3-core-helpers/src/errors.js:38:16)
      at RequestManager.send (node_modules/web3-core-requestmanager/src/index.js:128:32)
      at sendRequest (node_modules/web3-core-method/src/index.js:560:42)
      at Net.send [as getId] (node_modules/web3-core-method/src/index.js:581:13)
      at Function.<anonymous> (node_modules/zos/node_modules/zos-lib/src/artifacts/ZWeb3.ts:127:28)
      at Generator.next (<anonymous>)
      at node_modules/zos/node_modules/zos-lib/lib/artifacts/ZWeb3.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/zos/node_modules/zos-lib/lib/artifacts/ZWeb3.js:3:12)
      at Function.getNetwork (node_modules/zos/node_modules/zos-lib/lib/artifacts/ZWeb3.js:139:16)
      at Function.<anonymous> (node_modules/zos/node_modules/zos-lib/src/artifacts/ZWeb3.ts:131:35)
      at Generator.next (<anonymous>)
      at node_modules/zos/node_modules/zos-lib/lib/artifacts/ZWeb3.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/zos/node_modules/zos-lib/lib/artifacts/ZWeb3.js:3:12)
      at Function.getNetworkName (node_modules/zos/node_modules/zos-lib/lib/artifacts/ZWeb3.js:144:16)
      at Function.<anonymous> (node_modules/zos/node_modules/zos-lib/src/artifacts/ZWeb3.ts:123:25)
      at Generator.next (<anonymous>)
      at node_modules/zos/node_modules/zos-lib/lib/artifacts/ZWeb3.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/zos/node_modules/zos-lib/lib/artifacts/ZWeb3.js:3:12)
      at Function.isMainnet (node_modules/zos/node_modules/zos-lib/lib/artifacts/ZWeb3.js:134:16)
      at Object.<anonymous> (node_modules/zos/node_modules/zos-lib/src/utils/Transactions.ts:197:78)
      at Generator.next (<anonymous>)
      at node_modules/zos/node_modules/zos-lib/lib/utils/Transactions.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/zos/node_modules/zos-lib/lib/utils/Transactions.js:8:12)
      at Object._fixGasPrice (node_modules/zos/node_modules/zos-lib/lib/utils/Transactions.js:213:16)
      at Object.<anonymous> (node_modules/zos/node_modules/zos-lib/src/utils/Transactions.ts:90:16)
      at Generator.next (<anonymous>)
      at node_modules/zos/node_modules/zos-lib/lib/utils/Transactions.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/zos/node_modules/zos-lib/lib/utils/Transactions.js:8:12)
      at Object.deployContract (node_modules/zos/node_modules/zos-lib/lib/utils/Transactions.js:92:16)
      at Function.<anonymous> (node_modules/zos/node_modules/zos-lib/src/application/Package.ts:25:48)
      at Generator.next (<anonymous>)
      at node_modules/zos/node_modules/zos-lib/lib/application/Package.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/zos/node_modules/zos-lib/lib/application/Package.js:3:12)
      at Function.deploy (node_modules/zos/node_modules/zos-lib/lib/application/Package.js:30:16)
```

**Comment by jcarpanelli** [comment]
hey @crazyrabbitLTC, have you tried what we talked via slack (removing the `node_modules` folder and reinstalling both `zos` and `zos-lib`)?

**Comment by crazyrabbitLTC** [comment]
@jcarpanelli  you were correct: I introduced an error by uninstalling` zos@2.2.0 ` and then installing `zos@next` without removing zos-lib.  By following your instructions my tests now work. Thank you!
