### ISSUE TITLE
Creating a proxy for a contract with solidity libraries fails from the Project class

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#863]
Creating a proxy using `zos-lib` directly fails for a contract that requires Solidity libraries. When running `createProxy` for the first time for a contract, the `Project` class will attempt to deploy the logic contract, but will fail since it does not have its libraries linked.

```js
await myProject.createProxy(MyContractWithLibs, { initArgs: [myArg] });
```

The error thrown is the following (thanks @jachai for the report):
```
TypeError: Cannot read property 'match' of undefined
    at getSolidityLibNames (/Users/jretina/Programming/PROPSProject/props-token-distribution/node_modules/zos-lib/src/utils/Bytecode.ts:23:35)
    at Object.hasUnlinkedVariables (/Users/jretina/Programming/PROPSProject/props-token-distribution/node_modules/zos-lib/src/utils/Bytecode.ts:29:10)
    at Object.buildDeploymentCallData (/Users/jretina/Programming/PROPSProject/props-token-distribution/node_modules/zos-lib/src/utils/ABIs.ts:24:7)
    at Object.<anonymous> (/Users/jretina/Programming/PROPSProject/props-token-distribution/node_modules/zos-lib/src/utils/Transactions.ts:93:112)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jretina/Programming/PROPSProject/props-token-distribution/node_modules/zos-lib/lib/utils/Transactions.js:9:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Note that this works when called from the CLI, since the NetworkController takes care of linking the library automatically. It first uploads all solidity libraries at `uploadSolidityLibs`:

https://github.com/zeppelinos/zos/blob/a7600c23fd6fc5630a78bd5096675631a666f192/packages/cli/src/models/network/NetworkController.ts#L202-L214

And then links them for each contract at:

https://github.com/zeppelinos/zos/blob/a7600c23fd6fc5630a78bd5096675631a666f192/packages/cli/src/models/network/NetworkController.ts#L242-L246

A workaround is to manually deploy the solidity library, and then link it to the contract instance _before_ calling `createProxy`. Something along the lines of the following (untested):

```js
MyLibrary = Contracts.getFromLocal("MyLibrary")
const lib = await this.project.setImplementation(MyLibrary, "MyLibrary");
MyContractWithLibs.link({ "MyLibrary": lib.address });
await myProject.createProxy(MyContractWithLibs, { initArgs: [myArg] });
```

As a permanent solution, we need to move this logic from the controller to the project class, while preserving the deployed libraries addresses in the controller and network files.

**Comment by chentschel** [comment]
I'm having a similar issue after updating to 2.4.0. 

Calling createProxy() fails. 

```
contract = await project.createProxy(MyContract, {
      initMethod: 'initialize',
      initArgs: [
        owner,
        address_a,
        address_b,
        address_c,
        address_d
      ]
    });
```

```
     TypeError: Cannot read property 'toChecksumAddress' of undefined
      at Object.toAddress (node_modules/zos-lib/src/utils/Addresses.ts:12:21)
      at new ProxyAdmin (node_modules/zos-lib/src/proxy/ProxyAdmin.ts:39:20)
      at Function.<anonymous> (node_modules/zos-lib/src/proxy/ProxyAdmin.ts:34:12)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/zos-lib/lib/proxy/ProxyAdmin.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
