### ISSUE TITLE
`zos unpack` throws "TypeError: Cannot read property 'toLowerCase' of undefined"

### ISSUE THREAD

**Issue by jcarpanelli** [zeppelinos/zos#865]
It seems that when running `zos unpack` without providing any arguments, the `cli` throws `TypeError: Cannot read property 'toLowerCase' of undefined`. It should throw a friendlier error instead, for instance: `A kit name must be specified` or sth like that.

You can reproduce it just running:
```
foo@bar~$: zos unpack
```

Full error:
```
jota@zlenovo:~/work/zeppelin/samples/zos-sample$ zos unpack --verbose
[Error] TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.<anonymous> (/home/jota/work/zeppelin/zos/packages/cli/lib/scripts/unpack.js:22:33)
    at Generator.next (<anonymous>)
    at /home/jota/work/zeppelin/zos/packages/cli/lib/scripts/unpack.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/jota/work/zeppelin/zos/packages/cli/lib/scripts/unpack.js:3:12)
    at Object.unpack [as default] (/home/jota/work/zeppelin/zos/packages/cli/lib/scripts/unpack.js:21:12)
    at Command.<anonymous> (/home/jota/work/zeppelin/zos/packages/cli/lib/commands/unpack.js:25:31)
    at Generator.next (<anonymous>)
    at /home/jota/work/zeppelin/zos/packages/cli/lib/commands/unpack.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/jota/work/zeppelin/zos/packages/cli/lib/commands/unpack.js:3:12)
    at Command.action (/home/jota/work/zeppelin/zos/packages/cli/lib/commands/unpack.js:24:12)
    at Command.listener (/home/jota/work/zeppelin/zos/packages/cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:189:13)
    at Command.parseArgs (/home/jota/work/zeppelin/zos/packages/cli/node_modules/commander/index.js:654:12)
    at Command.parse (/home/jota/work/zeppelin/zos/packages/cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/jota/work/zeppelin/zos/packages/cli/lib/bin/zos-cli.js:28:19)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by spalladino** [comment]
Fixed by @ylv-io in #869
