### ISSUE TITLE
Build error in middle of npm install zos, please kindly help!

### ISSUE THREAD

**Issue by WillZhuang** [zeppelinos/zos#908]
Build error in middle of npm install zos, please kindly help!

### Environment:
ubuntu version : 18.04
node version: v10.15.3 （v11.15.0 also the same error）
npm version: 6.4.1
node-gyp version: v4.0.0
gcc g++ version: gcc (Ubuntu 8-20180414-1ubuntu2) 8.0.1

### error log:
```shell
➜  ~ yarn global add truffle zos
yarn global v1.16.0
[1/4] Resolving packages...
warning zos > lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
warning zos > zos-lib > lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
warning zos > web3 > web3-bzz > swarm-js > tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
warning zos > web3 > web3-bzz > swarm-js > fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
warning zos > web3-provider-engine > ethereumjs-block > merkle-patricia-tree > level-ws > xtend > object-keys@0.4.0: 
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/6] ⠐ waiting...
[-/6] ⠐ waiting...
[-/6] ⠐ waiting...
[4/6] ⠐ scrypt
error /home/user/.config/yarn/global/node_modules/scrypt: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/user/.config/yarn/global/node_modules/scrypt
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/user/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.config/yarn/global/node_modules/scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.node-gyp/10.15.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.node-gyp/10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/user/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/user/.node-gyp/10.15.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/user/.config/yarn/global/node_modules/scrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/user/.config/yarn/global/node_modules/scrypt/build'
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
  COPY Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
make: cc: Command not found
scrypt_wrapper.target.mk:116: recipe for target 'Release/obj.target/scrypt_wrapper/src/util/memlimit.o' failed
make: *** [Release/obj.target/scrypt_wrapper/src/util/memlimit.o] Error 127
make: Leaving directory '/home/user/.config/yarn/global/node_modules/scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-50-generic
gyp ERR! command "/home/user/.nvm/versions/node/v10.15.3/bin/node" "/home/user/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/.config/yarn/global/node_modules/scrypt


```

**Comment by WillZhuang** [comment]
I changed to ubuntu 16.04, and gcc version as below:
```
➜  ~ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

and zos npm install is OK.

**Comment by spalladino** [comment]
Glad you could fix it, Will. It's odd though, I'm on Ubuntu 18 myself, and the install goes fine. I'm on slightly more recent versions though: Ubuntu 18.10 and gcc 8.3.0. If you want to upgrade back to 18, you may want to give this a shot.
