### ISSUE TITLE
Error when printing errors in verbose mode

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#979]
When any error is thrown by the CLI in verbose mode, the logger fails and the following error is thrown instead:

```
/home/spalladino/Projects/zeppelinos/zos/packages/cli/node_modules/ansi-styles/index.js:16
	return `\u001B[${38 + offset};2;${rgb[0]};${rgb[1]};${rgb[2]}m`;
	                                     ^

TypeError: Cannot read property '0' of undefined
    at /home/spalladino/Projects/zeppelinos/zos/packages/cli/node_modules/ansi-styles/index.js:16:39
    at Function.<anonymous> (/home/spalladino/Projects/zeppelinos/zos/packages/cli/node_modules/chalk/index.js:82:63)
    at Object._log (/home/spalladino/Projects/zeppelinos/zos/packages/cli/node_modules/zos-lib/lib/utils/Logger.js:97:60)
    at Object.add (/home/spalladino/Projects/zeppelinos/zos/packages/cli/node_modules/zos-lib/lib/utils/Logger.js:63:14)
    at Function.exports.Loggy.(anonymous function).(anonymous function) [as error] (/home/spalladino/Projects/zeppelinos/zos/packages/cli/node_modules/zos-lib/lib/utils/Logger.js:156:98)
    at ErrorHandler.call (/home/spalladino/Projects/zeppelinos/zos/packages/cli/lib/models/errors/ErrorHandler.js:17:36)
    at process.cb (/home/spalladino/Projects/zeppelinos/zos/packages/cli/lib/bin/errors.js:8:70)
    at process.emit (events.js:182:13)
    at processEmit [as emit] (/home/spalladino/Projects/zeppelinos/zos/packages/cli/node_modules/signal-exit/index.js:155:32)
    at process._fatalException (internal/bootstrap/node.js:491:27)
```

**Comment by jcarpanelli** [comment]
This seems to be because `chalk` does not understand the color `redBright` when called using `chalk.keyword`:
```js
const coloredMessage = color ? chalk.keyword(color)(message) : message;
```

Will push a fix together with some tests for the new logger.
