### ISSUE TITLE
bug(arg-parsing): string args containing dashes cause error

### ISSUE THREAD

**Issue by gskapka** [zeppelinos/zos#981]
...per title. For a given `Contract` with an initializer argument of type `string`:

`zos create Contract --args string-withDash`

or 

`zos create Contract --args 'string-withDash'`

...both fail with:

```
[Error] Error: Error parsing arguments: SyntaxError: Unexpected token s in JSON at position 1
    at parseArgs (/home/user/.nvm/versions/node/v10.15.0/lib/node_modules/zos/lib/utils/input.js:39:15)
    at Object.parseInit (/home/user/.nvm/versions/node/v10.15.0/lib/node_modules/zos/lib/utils/input.js:50:20)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v10.15.0/lib/node_modules/zos/lib/prompts/init-params.js:23:48)
    at Generator.next (<anonymous>)
    at /home/user/.nvm/versions/node/v10.15.0/lib/node_modules/zos/lib/prompts/init-params.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/user/.nvm/versions/node/v10.15.0/lib/node_modules/zos/lib/prompts/init-params.js:3:12)
    at Object.promptForMethodParams [as default] (/home/user/.nvm/versions/node/v10.15.0/lib/node_modules/zos/lib/prompts/init-params.js:21:12)
    at Command.<anonymous> (/home/user/.nvm/versions/node/v10.15.0/lib/node_modules/zos/lib/commands/create.js:51:55)
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/.nvm/versions/node/v10.15.0/lib/node_modules/zos/lib/commands/create.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by spalladino** [comment]
Thanks for the report @gskapka! 

To fix this, we should decouple the method and args parsing in `input#parseMethodParams`. Instead of trying to parse both together, we should:
- Get the method name. If not set, go full interactive mode.
- Parse the arguments with `input#parseArray` and get the number of arguments passed in.
- Given the method name and the number of arguments, go to the ABI and retrieve it. Throw if it does not exist, or there is more than one method with that name or number of args (in which case tell the user to specify the fully qualified method name, like `initialize(string,uint256)`). 
- Given the method ABI info, use the input types to parse each argument according to its type using `input#parseArg`

This should allow us to delete `input#parseArgs` once and for all.
